name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # #for e2e test
    # services:
    #   - name: postgres
    #     image: postgres:16
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #     options: >-
    #       --health-cmd "pg_isready"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Set env for test
        run: |
          echo ENV=test >> .env
          echo DB_TYPE=postgres >> .env
          echo DB_HOST=localhost >> .env
          echo DB_PORT=5432 >> .env
          echo DB_USERNAME=postgres >> .env
          echo DB_PASSWORD=postgres >> .env
          echo DB_DATABASE=book-journey >> .env
          echo HASH_ROUNDS=10 >> .env
          echo ACCESS_TOKEN_SECRET=access_token_secret >> .env
          echo REFRESH_TOKEN_SECRET=refresh_token_secret >> .env

      - name: Build
        run: npm run build

      - name: Run test
        run: npm run test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/book-journey-nest
            git pull origin main
            npm ci --only=production
            npm run build
            pm2 restart main
