name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # #for e2e test
    # services:
    #   - name: postgres
    #     image: postgres:16
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #     options: >-
    #       --health-cmd "pg_isready"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set env for test
        run: |
          echo ENV=test >> .env
          echo DB_TYPE=postgres >> .env
          echo DB_HOST=localhost >> .env
          echo DB_PORT=5432 >> .env
          echo DB_USERNAME=postgres >> .env
          echo DB_PASSWORD=postgres >> .env
          echo DB_DATABASE=book-journey >> .env
          echo HASH_ROUNDS=10 >> .env
          echo ACCESS_TOKEN_SECRET=access_token_secret >> .env
          echo REFRESH_TOKEN_SECRET=refresh_token_secret >> .env

      - name: Build
        run: npm run build

      - name: Run test
        run: npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          region: ${{secrets.AWS_REGION}}
          application: book-journey
          environment: Book-journey-EB-env
          version_label: ${{github.run_id}}
          zip: deploy.zip
